http:
  port: "8081"

american:
  host: "training4-american-api-chale.us-e2.cloudhub.io"
  port: "80"
  basepath: "/"
  protocol: "HTTP"
  client_id: "a2229489757b4320b8890c213484668d"
  client_secret: "78D43496fE0947aFa4684aa778f1bb37"
  
training:
  host: "mu.learn.mulesoft.com"
  port: "80"
  basepath: "/"
  protocol: "HTTP"
  
delta:
  wsdl: "http://mu.learn.mulesoft.com/delta?wsdl"
  service: "TicketServiceService"
  port: "TicketServicePort"