http:
  port: "8081"
  
sfdc:
  username: "jesus1@training.com"
  password: "Sandos1377A3"
  token: "lBkuNTTtRprjKbiBK65GRMYN"

file:
  accountsDir: "D:/PuntoSingular/minosoft/APDevFundamentals4.3_studentFiles_SP_02feb2021/resources"
  
db:
  host: "mudb.learn.mulesoft.com"
  port: "3306"
  user: "mule"
  password: "mule"
  database: "training"